<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            [
                'id' => 1,
                'name' => 'Create User',
                'slug' => 'create.user',
                'module' => 'User',
                'description' => 'User Management',
                'status' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Edit User',
                'slug' => 'edit.user',
                'module' => 'User',
                'description' => 'User Management',
                'status' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Delete User',
                'slug' => 'delete.user',
                'module' => 'User',
                'description' => 'User Management',
                'status' => 1,
            ],
            [
                'id' => 4,
                'name' => 'View User',
                'slug' => 'view.user',
                'module' => 'User',
                'description' => 'User Management',
                'status' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Create Role',
                'slug' => 'create.role',
                'module' => 'Role & Permission',
                'description' => 'Role & Permission',
                'status' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Edit Role',
                'slug' => 'edit.role',
                'module' => 'Role & Permission',
                'description' => 'Role & Permission',
                'status' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Delete Role',
                'slug' => 'delete.role',
                'module' => 'Role & Permission',
                'description' => 'Role & Permission',
                'status' => 1,
            ],
            [
                'id' => 8,
                'name' => 'View Role',
                'slug' => 'view.role',
                'module' => 'Role & Permission',
                'description' => 'Role & Permission',
                'status' => 1,
            ],
            [
                'id' => 9,
                'name' => 'Create Student',
                'slug' => 'create.student',
                'module' => 'Student Management',
                'description' => 'Student Management',
                'status' => 0,
            ],
            [
                'id' => 10,
                'name' => 'Edit Student',
                'slug' => 'edit.student',
                'module' => 'Student Management',
                'description' => 'Student Management',
                'status' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Delete Student',
                'slug' => 'delete.student',
                'module' => 'Student Management',
                'description' => 'Student Management',
                'status' => 0,
            ],
            [
                'id' => 12,
                'name' => 'View Student',
                'slug' => 'view.student',
                'module' => 'Student Management',
                'description' => 'Student Management',
                'status' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Create Staff',
                'slug' => 'create.staff',
                'module' => 'Staff',
                'description' => 'Staff Management',
                'status' => 1,
            ],
            [
                'id' => 14,
                'name' => 'Edit Staff',
                'slug' => 'edit.staff',
                'module' => 'Staff',
                'description' => 'Staff Management',
                'status' => 1,
            ],
            [
                'id' => 15,
                'name' => 'Delete Staff',
                'slug' => 'delete.staff',
                'module' => 'Staff',
                'description' => 'Staff Management',
                'status' => 1,
            ],
            [
                'id' => 16,
                'name' => 'View Staff',
                'slug' => 'view.staff',
                'module' => 'Staff',
                'description' => 'Staff Management',
                'status' => 1,
            ],
            [
                'id' => 17,
                'name' => 'Create Staff Attendance',
                'slug' => 'create.staff.attendance',
                'module' => 'Staff Attendance',
                'description' => 'Staff Attendance',
                'status' => 1,
            ],
            [
                'id' => 18,
                'name' => 'Edit Staff Attendance',
                'slug' => 'edit.staff.attendance',
                'module' => 'Staff Attendance',
                'description' => 'Staff Attendance',
                'status' => 1,
            ],
            [
                'id' => 19,
                'name' => 'Delete Staff Attendance',
                'slug' => 'delete.staff.attendance',
                'module' => 'Staff Attendance',
                'description' => 'Staff Attendance',
                'status' => 1,
            ],
            [
                'id' => 20,
                'name' => 'View Staff Attendance',
                'slug' => 'view.staff.attendance',
                'module' => 'Staff Attendance',
                'description' => 'Staff Attendance',
                'status' => 1,
            ],
            [
                'id' => 21,
                'name' => 'Create Student Attendance',
                'slug' => 'create.student.attendance',
                'module' => 'Student Attendance',
                'description' => 'Student Attendance',
                'status' => 1,
            ],
            [
                'id' => 22,
                'name' => 'Edit Student Attendance',
                'slug' => 'edit.student.attendance',
                'module' => 'Student Attendance',
                'description' => 'Student Attendance',
                'status' => 1,
            ],
            [
                'id' => 23,
                'name' => 'Delete Student Attendance',
                'slug' => 'delete.student.attendance',
                'module' => 'Student Attendance',
                'description' => 'Student Attendance',
                'status' => 1,
            ],
            [
                'id' => 24,
                'name' => 'View Student Attendance',
                'slug' => 'view.student.attendance',
                'module' => 'Student Attendance',
                'description' => 'Student Attendance',
                'status' => 1,
            ],
            [
                'id' => 25,
                'name' => 'Create Class',
                'slug' => 'create.class',
                'module' => 'Class Management',
                'description' => 'Class Management',
                'status' => 1,
            ],
            [
                'id' => 26,
                'name' => 'Edit Class',
                'slug' => 'edit.class',
                'module' => 'Class Management',
                'description' => 'Class Management',
                'status' => 1,
            ],
            [
                'id' => 27,
                'name' => 'Delete Class',
                'slug' => 'delete.class',
                'module' => 'Class Management',
                'description' => 'Class Management',
                'status' => 1,
            ],
            [
                'id' => 28,
                'name' => 'View Class',
                'slug' => 'view.class',
                'module' => 'Class Management',
                'description' => 'Class Management',
                'status' => 1,
            ],
            [
                'id' => 29,
                'name' => 'Create Section',
                'slug' => 'create.section',
                'module' => 'Section Management',
                'description' => 'Section Management',
                'status' => 1,
            ],
            [
                'id' => 30,
                'name' => 'Edit Section',
                'slug' => 'edit.section',
                'module' => 'Section Management',
                'description' => 'Section Management',
                'status' => 1,
            ],
            [
                'id' => 31,
                'name' => 'Delete Section',
                'slug' => 'delete.section',
                'module' => 'Section Management',
                'description' => 'Section Management',
                'status' => 1,
            ],
            [
                'id' => 32,
                'name' => 'View Section',
                'slug' => 'view.section',
                'module' => 'Section Management',
                'description' => 'Section Management',
                'status' => 1,
            ],
            [
                'id' => 33,
                'name' => 'Create Student Admission',
                'slug' => 'create.student.admission',
                'module' => 'Student Admission Management',
                'description' => 'Student Admission Management',
                'status' => 1,
            ],
            [
                'id' => 34,
                'name' => 'Edit Student Admission',
                'slug' => 'edit.student.admission',
                'module' => 'Student Admission Management',
                'description' => 'Student Admission Management',
                'status' => 1,
            ],
            [
                'id' => 35,
                'name' => 'Delete Student Admission',
                'slug' => 'delete.student.admission',
                'module' => 'Student Admission Management',
                'description' => 'Student Admission Management',
                'status' => 1,
            ],
            [
                'id' => 36,
                'name' => 'View Student Admission',
                'slug' => 'view.student.admission',
                'module' => 'Student Admission Management',
                'description' => 'Student Admission Management',
                'status' => 1,
            ],
            [
                'id' => 37,
                'name' => 'Create Subject',
                'slug' => 'create.subject',
                'module' => 'Subject Management',
                'description' => 'Subject Management',
                'status' => 1,
            ],
            [
                'id' => 38,
                'name' => 'Edit Subject',
                'slug' => 'edit.subject',
                'module' => 'Subject Management',
                'description' => 'Subject Management',
                'status' => 1,
            ],
            [
                'id' => 39,
                'name' => 'Delete Subject',
                'slug' => 'delete.subject',
                'module' => 'Subject Management',
                'description' => 'Subject Management',
                'status' => 1,
            ],
            [
                'id' => 40,
                'name' => 'View Subject',
                'slug' => 'view.subject',
                'module' => 'Subject Management',
                'description' => 'Subject Management',
                'status' => 1,
            ],
            [
                'id' => 41,
                'name' => 'Create Academic Session',
                'slug' => 'create.academic.session',
                'module' => 'Academic Year Setup',
                'description' => 'Academic Year Setup',
                'status' => 1,
            ],
            [
                'id' => 42,
                'name' => 'Edit Academic Session',
                'slug' => 'edit.academic.session',
                'module' => 'Academic Year Setup',
                'description' => 'Academic Year Setup',
                'status' => 1,
            ],
            [
                'id' => 43,
                'name' => 'Delete Academic Session',
                'slug' => 'delete.academic.session',
                'module' => 'Academic Year Setup',
                'description' => 'Academic Year Setup',
                'status' => 1,
            ],
            [
                'id' => 44,
                'name' => 'View Academic Session',
                'slug' => 'view.academic.session',
                'module' => 'Academic Year Setup',
                'description' => 'Academic Year Setup',
                'status' => 1,
            ],
            [
                'id' => 45,
                'name' => 'Create Fee Category',
                'slug' => 'create.fee.category',
                'module' => 'Fee Category',
                'description' => 'Fee Category Management',
                'status' => 1,
            ],
            [
                'id' => 46,
                'name' => 'Edit Fee Category',
                'slug' => 'edit.fee.category',
                'module' => 'Fee Category',
                'description' => 'Fee Category Management',
                'status' => 1,
            ],
            [
                'id' => 47,
                'name' => 'Delete Fee Category',
                'slug' => 'delete.fee.category',
                'module' => 'Fee Category',
                'description' => 'Fee Category Management',
                'status' => 1,
            ],
            [
                'id' => 48,
                'name' => 'View Fee Category',
                'slug' => 'view.fee.category',
                'module' => 'Fee Category',
                'description' => 'Fee Category Management',
                'status' => 1,
            ],
            [
                'id' => 49,
                'name' => 'Assign Fee',
                'slug' => 'assign.fee',
                'module' => 'Fee Collection',
                'description' => 'Fee Collection Management',
                'status' => 1,
            ],
            [
                'id' => 50,
                'name' => 'Collect Fee',
                'slug' => 'collect.fee',
                'module' => 'Fee Collection',
                'description' => 'Fee Collection Management',
                'status' => 1,
            ],
            [
                'id' => 51,
                'name' => 'View Fee Dashboard',
                'slug' => 'view.fee.dashboard',
                'module' => 'Fee Collection',
                'description' => 'Fee Collection Management',
                'status' => 1,
            ],
            [
                'id' => 52,
                'name' => 'View Fee History',
                'slug' => 'view.fee.history',
                'module' => 'Fee Collection',
                'description' => 'Fee Collection Management',
                'status' => 1,
            ],
            [
                'id' => 53,
                'name' => 'Create Exam',
                'slug' => 'create.exam',
                'module' => 'Exam Management',
                'description' => 'Exam Management',
                'status' => 1,
            ],
            [
                'id' => 54,
                'name' => 'Edit Exam',
                'slug' => 'edit.exam',
                'module' => 'Exam Management',
                'description' => 'Exam Management',
                'status' => 1,
            ],
            [
                'id' => 55,
                'name' => 'Delete Exam',
                'slug' => 'delete.exam',
                'module' => 'Exam Management',
                'description' => 'Exam Management',
                'status' => 1,
            ],
            [
                'id' => 56,
                'name' => 'View Exam',
                'slug' => 'view.exam',
                'module' => 'Exam Management',
                'description' => 'Exam Management',
                'status' => 1,
            ],
            [
                'id' => 57,
                'name' => 'Assign Marks',
                'slug' => 'assign.marks',
                'module' => 'Exam Management',
                'description' => 'Exam Result Management',
                'status' => 1,
            ],
            [
                'id' => 58,
                'name' => 'View Results',
                'slug' => 'view.results',
                'module' => 'Exam Management',
                'description' => 'Exam Result Management',
                'status' => 1,
            ],
            [
                'id' => 59,
                'name' => 'Generate Report Card',
                'slug' => 'generate.report.card',
                'module' => 'Exam Management',
                'description' => 'Exam Result Management',
                'status' => 1,
            ],
            [
                'id' => 60,
                'name' => 'Create Homework',
                'slug' => 'create.homework',
                'module' => 'Homework Management',
                'description' => 'Homework Management',
                'status' => 1,
            ],
            [
                'id' => 61,
                'name' => 'Edit Homework',
                'slug' => 'edit.homework',
                'module' => 'Homework Management',
                'description' => 'Homework Management',
                'status' => 1,
            ],
            [
                'id' => 62,
                'name' => 'Delete Homework',
                'slug' => 'delete.homework',
                'module' => 'Homework Management',
                'description' => 'Homework Management',
                'status' => 1,
            ],
            [
                'id' => 63,
                'name' => 'View Homework',
                'slug' => 'view.homework',
                'module' => 'Homework Management',
                'description' => 'Homework Management',
                'status' => 1,
            ],
            [
                'id' => 64,
                'name' => 'View Student List Report',
                'slug' => 'view.student.list.report',
                'module' => 'Reports',
                'description' => 'View Student List Report',
                'status' => 1,
            ],
            [
                'id' => 65,
                'name' => 'View Attendance Report',
                'slug' => 'view.attendance.report',
                'module' => 'Reports',
                'description' => 'View Attendance Report',
                'status' => 1,
            ],
            [
                'id' => 66,
                'name' => 'View Fee Report',
                'slug' => 'view.fee.report',
                'module' => 'Reports',
                'description' => 'View Fee Report',
                'status' => 1,
            ],
            [
                'id' => 67,
                'name' => 'View Exam Result Report',
                'slug' => 'view.exam.result.report',
                'module' => 'Reports',
                'description' => 'View Exam Result Report',
                'status' => 1,
            ],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate([
                'id' => $permission['id']
            ], [
                'name' => $permission['name'],
                'slug' => $permission['slug'],
                'module' => $permission['module'],
                'description' => $permission['description'],
                'status' => $permission['status'],
            ]);
        }
    }
}
